
import { Language, Pet, ServiceProvider, TranslationKey } from './types';

export const TRANSLATIONS: Record<Language, Record<TranslationKey, string>> = {
  [Language.PT]: {
    heroTitle: "O Mundo do Seu Pet em Um Só Lugar",
    heroSubtitle: "Conecte-se, cuide e ame. A plataforma completa para o seu melhor amigo.",
    ctaStart: "Começar Agora",
    ctaLogin: "Entrar",
    planBasic: "AnyBasic",
    planStart: "AnyStart",
    planPremium: "AnyPremium",
    perMonth: "/mês",
    features: "Recursos",
    loginTitle: "Acesse sua Conta",
    email: "E-mail",
    password: "Senha",
    loginButton: "Entrar na Plataforma",
    dashHome: "Início",
    dashAdoption: "Adoção",
    dashDating: "Namoro",
    dashHealth: "Carteirinha",
    dashServices: "Agendamentos",
    dashProfile: "Perfil do Pet",
    logout: "Sair",
    welcome: "Bem-vindo de volta",
    myPets: "Meus Pets",
    vaccines: "Vacinas",
    serviceVet: "Veterinários",
    serviceGroom: "Petshops",
    serviceHotel: "Hotéis",
    serviceWalker: "Dog Walkers",
    bookNow: "Agendar",
    adoptMe: "Me Adote",
    match: "Dar Match",
    generateBio: "Gerar Bio com IA",
    bioPlaceholder: "Escreva sobre seu pet...",
    priceFree: "Grátis",
    priceStart: "R$ 29,90",
    pricePremium: "R$ 59,90",
    popular: "POPULAR",
    featProfile: "Perfil do Pet",
    featAdoption: "Acesso à Adoção",
    featBasic: "Tudo do Basic",
    featVaccines: "Carteira de Vacinação Digital",
    featScheduling: "Agendamento de Serviços",
    featStart: "Tudo do Start",
    featDating: "Namoro / Cruzamento",
    featAIBio: "Gerador de Bio com IA",
    featSupport: "Suporte Prioritário",
    btnChooseBasic: "Escolher Basic",
    btnChooseStart: "Escolher Start",
    btnChoosePremium: "Escolher Premium",
    signupTitle: "Crie sua Conta",
    name: "Nome Completo",
    confirmPassword: "Confirmar Senha",
    signupButton: "Cadastrar",
    haveAccount: "Já tem uma conta? Entrar",
    noAccount: "Não tem uma conta? Cadastre-se",
    createAccount: "Criar Conta",
    editProfile: "Editar Perfil",
    saveChanges: "Salvar Alterações",
    cancel: "Cancelar",
    weight: "Peso (kg)",
    photoUrl: "URL da Foto",
    ageLabel: "Idade (anos)",
    breedLabel: "Raça",
    changePhoto: "Alterar Foto",
    userProfile: "Dados do Dono",
    switchPet: "Trocar Pet",
    addNewPet: "Adicionar Novo Pet",
    noPets: "Nenhum pet encontrado",
    createFirstPet: "Cadastre seu primeiro pet",
    userSettings: "Minha Conta",
    phone: "Telefone",
    petName: "Nome do Pet",
    petType: "Tipo de Animal",
    selectPet: "Selecione um Pet",
    deletePet: "Excluir Pet",
    confirmDeletePet: "Tem certeza que deseja excluir este pet? Essa ação não pode ser desfeita.",
    deletePetWarning: "Excluir este perfil permanentemente",
    currentPlan: "Plano Atual",
    upgradePlan: "Alterar Plano",
    planBenefits: "Benefícios do seu plano",
    managePlan: "Gerenciar Assinatura",
    typeDog: "Cachorro",
    typeCat: "Gato",
    typeBird: "Pássaro",
    typeOther: "Outro",
    healthVaccine: "Vacina",
    healthDate: "Data da Aplicação",
    healthNextDue: "Próxima Dose",
    healthStatus: "Status",
    healthNoRecords: "Nenhum registro de vacina encontrado.",
    healthTip: "Dica: Mantenha a carteirinha de vacinação atualizada para acessar hotéis e creches.",
    planDescBasic: "Acesso ao Perfil e Adoção",
    planDescStart: "Vacinas, Agendamentos e Recursos Básicos",
    planDescPremium: "Acesso Total, Namoro, IA e Suporte Prioritário",
    availableForDatingLabel: "Disponível para Namoro/Cruza",
    datingPlanWarning: "Recurso exclusivo para plano Premium!",
    featureLocked: "Funcionalidade Bloqueada",
    upgradeToAccess: "Faça upgrade do seu plano para acessar este recurso.",
    unlockNow: "Desbloquear Agora",
    tooltipProfile: "Gerencie as informações e fotos do seu pet.",
    tooltipAdoption: "Encontre um novo amigo ou adote.",
    tooltipDating: "Encontre o par perfeito para seu pet.",
    tooltipHealth: "Controle de vacinas e saúde.",
    tooltipServices: "Agende veterinários, banho e tosa.",
    reqPlanBasic: "Plano Basic ou superior",
    reqPlanStart: "Requer Plano Start",
    reqPlanPremium: "Requer Plano Premium",
    landingAdoptionTitle: "Encontre seu novo melhor amigo",
    landingAdoptionSubtitle: "Centenas de pets estão esperando por um lar cheio de amor. Faça a diferença hoje.",
    landingAdoptionBtn: "Ver Pets para Adoção",
    publicAdoptionTitle: "Adoção Responsável",
    publicAdoptionSubtitle: "Estes amigos estão procurando um lar. Navegue, apaixone-se e entre em contato.",
    backToHome: "Voltar ao Início",
    interestBtn: "Tenho Interesse"
  },
  [Language.EN]: {
    heroTitle: "Your Pet's World in One Place",
    heroSubtitle: "Connect, care, and love. The complete platform for your best friend.",
    ctaStart: "Get Started",
    ctaLogin: "Login",
    planBasic: "AnyBasic",
    planStart: "AnyStart",
    planPremium: "AnyPremium",
    perMonth: "/month",
    features: "Features",
    loginTitle: "Access Account",
    email: "Email",
    password: "Password",
    loginButton: "Enter Platform",
    dashHome: "Home",
    dashAdoption: "Adoption",
    dashDating: "Dating",
    dashHealth: "Health Card",
    dashServices: "Services",
    dashProfile: "Pet Profile",
    logout: "Logout",
    welcome: "Welcome back",
    myPets: "My Pets",
    vaccines: "Vaccines",
    serviceVet: "Vets",
    serviceGroom: "Grooming",
    serviceHotel: "Hotels",
    serviceWalker: "Dog Walkers",
    bookNow: "Book Now",
    adoptMe: "Adopt Me",
    match: "Match",
    generateBio: "Generate Bio with AI",
    bioPlaceholder: "Write about your pet...",
    priceFree: "Free",
    priceStart: "$9.90",
    pricePremium: "$19.90",
    popular: "POPULAR",
    featProfile: "Pet Profile",
    featAdoption: "Adoption Access",
    featBasic: "Everything in Basic",
    featVaccines: "Vaccination Card",
    featScheduling: "Service Scheduling",
    featStart: "Everything in Start",
    featDating: "Dating / Breeding",
    featAIBio: "AI Bio Generator",
    featSupport: "Priority Support",
    btnChooseBasic: "Choose Basic",
    btnChooseStart: "Choose Start",
    btnChoosePremium: "Choose Premium",
    signupTitle: "Create Account",
    name: "Full Name",
    confirmPassword: "Confirm Password",
    signupButton: "Sign Up",
    haveAccount: "Already have an account? Login",
    noAccount: "Don't have an account? Sign Up",
    createAccount: "Create Account",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    weight: "Weight (kg)",
    photoUrl: "Photo URL",
    ageLabel: "Age (years)",
    breedLabel: "Breed",
    changePhoto: "Change Photo",
    userProfile: "Owner Details",
    switchPet: "Switch Pet",
    addNewPet: "Add New Pet",
    noPets: "No pets found",
    createFirstPet: "Register your first pet",
    userSettings: "My Account",
    phone: "Phone",
    petName: "Pet Name",
    petType: "Animal Type",
    selectPet: "Select a Pet",
    deletePet: "Delete Pet",
    confirmDeletePet: "Are you sure you want to delete this pet? This action cannot be undone.",
    deletePetWarning: "Permanently delete this profile",
    currentPlan: "Current Plan",
    upgradePlan: "Change Plan",
    planBenefits: "Your plan benefits",
    managePlan: "Manage Subscription",
    typeDog: "Dog",
    typeCat: "Cat",
    typeBird: "Bird",
    typeOther: "Other",
    healthVaccine: "Vaccine",
    healthDate: "Date Given",
    healthNextDue: "Next Due",
    healthStatus: "Status",
    healthNoRecords: "No vaccine records found.",
    healthTip: "Tip: Keep your vaccination card updated to access Pet Hotels and Daycare services.",
    planDescBasic: "Profile & Adoption Access",
    planDescStart: "Vaccines, Scheduling, Basic Features",
    planDescPremium: "Full Access, Dating, AI, Priority Support",
    availableForDatingLabel: "Available for Dating/Breeding",
    datingPlanWarning: "This is a Premium plan feature!",
    featureLocked: "Feature Locked",
    upgradeToAccess: "Upgrade your plan to access this feature.",
    unlockNow: "Unlock Now",
    tooltipProfile: "Manage your pet's information and photos.",
    tooltipAdoption: "Find a new friend or adopt.",
    tooltipDating: "Find the perfect match for your pet.",
    tooltipHealth: "Track vaccines and health records.",
    tooltipServices: "Book vets, grooming, and more.",
    reqPlanBasic: "Basic Plan or higher",
    reqPlanStart: "Requires Start Plan",
    reqPlanPremium: "Requires Premium Plan",
    landingAdoptionTitle: "Find Your New Best Friend",
    landingAdoptionSubtitle: "Hundreds of pets are waiting for a loving home. Make a difference today.",
    landingAdoptionBtn: "View Pets for Adoption",
    publicAdoptionTitle: "Responsible Adoption",
    publicAdoptionSubtitle: "These friends are looking for a home. Browse, fall in love, and get in touch.",
    backToHome: "Back to Home",
    interestBtn: "I'm Interested"
  },
  [Language.ES]: {
    heroTitle: "El Mundo de tu Mascota en un Solo Lugar",
    heroSubtitle: "Conecta, cuida y ama. La plataforma completa para tu mejor amigo.",
    ctaStart: "Empezar Ahora",
    ctaLogin: "Ingresar",
    planBasic: "AnyBasic",
    planStart: "AnyStart",
    planPremium: "AnyPremium",
    perMonth: "/mes",
    features: "Características",
    loginTitle: "Acceso",
    email: "Correo",
    password: "Clave",
    loginButton: "Entrar a la Plataforma",
    dashHome: "Inicio",
    dashAdoption: "Adopción",
    dashDating: "Citas",
    dashHealth: "Cartilla",
    dashServices: "Servicios",
    dashProfile: "Perfil de Mascota",
    logout: "Salir",
    welcome: "Bienvenido de nuevo",
    myPets: "Mis Mascotas",
    vaccines: "Vacunas",
    serviceVet: "Veterinarios",
    serviceGroom: "Peluquería",
    serviceHotel: "Hoteles",
    serviceWalker: "Paseadores",
    bookNow: "Reservar",
    adoptMe: "Adóptame",
    match: "Coincidir",
    generateBio: "Generar Bio con IA",
    bioPlaceholder: "Escribe sobre tu mascota...",
    priceFree: "Gratis",
    priceStart: "$9.90",
    pricePremium: "$19.90",
    popular: "POPULAR",
    featProfile: "Perfil de Mascota",
    featAdoption: "Acceso a Adopción",
    featBasic: "Todo lo de Basic",
    featVaccines: "Cartilla de Vacunación",
    featScheduling: "Reserva de Servicios",
    featStart: "Todo lo de Start",
    featDating: "Citas / Cría",
    featAIBio: "Generador de Bio IA",
    featSupport: "Soporte Prioritario",
    btnChooseBasic: "Elegir Basic",
    btnChooseStart: "Elegir Start",
    btnChoosePremium: "Elegir Premium",
    signupTitle: "Crear Cuenta",
    name: "Nombre Completo",
    confirmPassword: "Confirmar Clave",
    signupButton: "Registrarse",
    haveAccount: "¿Ya tienes cuenta? Ingresar",
    noAccount: "¿No tienes cuenta? Regístrate",
    createAccount: "Crear Cuenta",
    editProfile: "Editar Perfil",
    saveChanges: "Guardar Cambios",
    cancel: "Cancelar",
    weight: "Peso (kg)",
    photoUrl: "URL de Foto",
    ageLabel: "Edad (años)",
    breedLabel: "Raza",
    changePhoto: "Cambiar Foto",
    userProfile: "Datos del Dueño",
    switchPet: "Cambiar Mascota",
    addNewPet: "Agregar Nueva Mascota",
    noPets: "No se encontraron mascotas",
    createFirstPet: "Registra tu primera mascota",
    userSettings: "Mi Cuenta",
    phone: "Teléfono",
    petName: "Nombre de Mascota",
    petType: "Tipo de Animal",
    selectPet: "Selecciona una Mascota",
    deletePet: "Eliminar Mascota",
    confirmDeletePet: "¿Estás seguro de que deseas eliminar esta mascota? Esta acción no se puede deshacer.",
    deletePetWarning: "Eliminar permanentemente este perfil",
    currentPlan: "Plan Actual",
    upgradePlan: "Cambiar Plan",
    planBenefits: "Beneficios de tu plan",
    managePlan: "Gestionar Suscripción",
    typeDog: "Perro",
    typeCat: "Gato",
    typeBird: "Pájaro",
    typeOther: "Otro",
    healthVaccine: "Vacuna",
    healthDate: "Fecha de Aplicación",
    healthNextDue: "Próxima Dosis",
    healthStatus: "Estado",
    healthNoRecords: "No se encontraron registros de vacunas.",
    healthTip: "Consejo: Mantén la cartilla de vacunación actualizada para acceder a hoteles y guarderías.",
    planDescBasic: "Acceso a Perfil y Adopción",
    planDescStart: "Vacunas, Reservas y Funciones Básicas",
    planDescPremium: "Acceso Total, Citas, IA y Soporte",
    availableForDatingLabel: "Disponible para Citas/Cría",
    datingPlanWarning: "¡Función exclusiva del plan Premium!",
    featureLocked: "Función Bloqueada",
    upgradeToAccess: "Mejora tu plan para acceder a esta función.",
    unlockNow: "Desbloquear Ahora",
    tooltipProfile: "Gestiona la información y fotos de tu mascota.",
    tooltipAdoption: "Encuentra un nuevo amigo o adopta.",
    tooltipDating: "Encuentra la pareja perfecta para tu mascota.",
    tooltipHealth: "Seguimiento de vacunas y salud.",
    tooltipServices: "Reserva veterinarios, peluquería y más.",
    reqPlanBasic: "Plan Basic o superior",
    reqPlanStart: "Requiere Plan Start",
    reqPlanPremium: "Requiere Plan Premium",
    landingAdoptionTitle: "Encuentra tu nuevo mejor amigo",
    landingAdoptionSubtitle: "Cientos de mascotas esperan un hogar lleno de amor. Haz la diferencia hoy.",
    landingAdoptionBtn: "Ver Mascotas en Adopción",
    publicAdoptionTitle: "Adopción Responsable",
    publicAdoptionSubtitle: "Estos amigos buscan un hogar. Navega, enamórate y contáctanos.",
    backToHome: "Volver al Inicio",
    interestBtn: "Me Interesa"
  }
};

export const MOCK_ADOPTION_PETS: Pet[] = [
  { id: '1', name: 'Thor', breed: 'Golden Retriever', age: 2, type: 'dog', image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=400&q=80', bio: 'Friendly and energetic.' },
  { id: '2', name: 'Luna', breed: 'Siamese', age: 1, type: 'cat', image: 'https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&w=400&q=80', bio: 'Quiet and loving.' },
  { id: '3', name: 'Bob', breed: 'Bulldog', age: 4, type: 'dog', image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=400&q=80', bio: 'Loves sleeping.' },
];

export const MOCK_DATING_PETS: Pet[] = [
  { id: '4', name: 'Bella', breed: 'Poodle', age: 3, type: 'dog', image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=400&q=80', bio: 'Looking for a playdate.' },
  { id: '5', name: 'Max', breed: 'German Shepherd', age: 3, type: 'dog', image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?auto=format&fit=crop&w=400&q=80', bio: 'Very active and protective.' },
];

export const MOCK_SERVICES: ServiceProvider[] = [
  { id: '1', name: 'Dr. Dolittle Clinic', type: 'veterinarian', rating: 4.8, image: 'https://picsum.photos/200/200?random=10' },
  { id: '2', name: 'Happy Paws Grooming', type: 'petshop', rating: 4.5, image: 'https://picsum.photos/200/200?random=11' },
  { id: '3', name: 'Walkies with Sarah', type: 'dogwalker', rating: 5.0, image: 'https://picsum.photos/200/200?random=12' },
  { id: '4', name: 'Pet Paradise Hotel', type: 'hotel', rating: 4.7, image: 'https://picsum.photos/200/200?random=13' },
];

export const MOCK_DAILY_PHOTOS = [
  { url: 'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?q=80&w=1000&auto=format&fit=crop', caption: 'Rex no Parque' },
  { url: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?q=80&w=1000&auto=format&fit=crop', caption: 'Mia Relaxando' },
  { url: 'https://images.unsplash.com/photo-1453227588063-bb302b62f50b?q=80&w=1000&auto=format&fit=crop', caption: 'Hora da soneca' },
  { url: 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?q=80&w=1000&auto=format&fit=crop', caption: 'Aventuras na neve' },
];