
import { Language, Pet, ServiceProvider, TranslationKey } from './types';

export const TRANSLATIONS: Record<Language, Record<TranslationKey, string>> = {
  [Language.PT]: {
    heroTitle: "O Mundo do Seu Pet em Um Só Lugar",
    heroSubtitle: "Conecte-se, cuide e ame. A plataforma completa para o seu melhor amigo.",
    ctaStart: "Começar Agora",
    ctaLogin: "Entrar",
    planBasic: "AnyBasic",
    planStart: "AnyStart",
    planPremium: "AnyPremium",
    perMonth: "/mês",
    features: "Recursos",
    loginTitle: "Acesse sua Conta",
    email: "E-mail",
    password: "Senha",
    loginButton: "Entrar na Plataforma",
    dashHome: "Início",
    dashAdoption: "Adoção",
    dashDating: "Namoro",
    dashHealth: "Carteirinha",
    dashServices: "Agendamentos",
    dashProfile: "Perfil do Pet",
    logout: "Sair",
    welcome: "Bem-vindo de volta",
    myPets: "Meus Pets",
    vaccines: "Vacinas",
    serviceVet: "Veterinários",
    serviceGroom: "Petshops",
    serviceHotel: "Hotéis",
    serviceWalker: "Dog Walkers",
    bookNow: "Agendar",
    adoptMe: "Me Adote",
    match: "Dar Match",
    generateBio: "Gerar Bio com IA",
    bioPlaceholder: "Escreva sobre seu pet...",
    priceFree: "Grátis",
    priceStart: "R$ 29,90",
    pricePremium: "R$ 59,90",
    popular: "POPULAR",
    featProfile: "Perfil do Pet",
    featAdoption: "Acesso à Adoção",
    featBasic: "Tudo do Basic",
    featVaccines: "Carteira de Vacinação Digital",
    featScheduling: "Agendamento de Serviços",
    featStart: "Tudo do Start",
    featDating: "Namoro / Cruzamento",
    featAIBio: "Gerador de Bio com IA",
    featSupport: "Suporte Prioritário",
    btnChooseBasic: "Escolher Basic",
    btnChooseStart: "Escolher Start",
    btnChoosePremium: "Escolher Premium",
    signupTitle: "Crie sua Conta",
    name: "Nome Completo",
    confirmPassword: "Confirmar Senha",
    signupButton: "Cadastrar",
    haveAccount: "Já tem uma conta? Entrar",
    noAccount: "Não tem uma conta? Cadastre-se",
    createAccount: "Criar Conta",
    editProfile: "Editar Perfil",
    saveChanges: "Salvar Alterações",
    cancel: "Cancelar",
    weight: "Peso (kg)",
    photoUrl: "URL da Foto",
    ageLabel: "Idade (anos)",
    breedLabel: "Raça",
    changePhoto: "Alterar Foto",
    userProfile: "Dados do Dono",
    switchPet: "Trocar Pet",
    addNewPet: "Adicionar Novo Pet",
    noPets: "Nenhum pet encontrado",
    createFirstPet: "Cadastre seu primeiro pet",
    userSettings: "Minha Conta",
    phone: "Telefone",
    petName: "Nome do Pet",
    petType: "Tipo de Animal",
    selectPet: "Selecione um Pet",
    deletePet: "Excluir Pet",
    confirmDeletePet: "Tem certeza que deseja excluir este pet? Essa ação não pode ser desfeita.",
    deletePetWarning: "Excluir este perfil permanentemente",
    currentPlan: "Plano Atual",
    upgradePlan: "Alterar Plano",
    planBenefits: "Benefícios do seu plano",
    managePlan: "Gerenciar Assinatura",
    typeDog: "Cachorro",
    typeCat: "Gato",
    typeBird: "Pássaro",
    typeOther: "Outro",
    healthVaccine: "Vacina",
    healthDate: "Data da Aplicação",
    healthNextDue: "Próxima Dose",
    healthStatus: "Status",
    healthNoRecords: "Nenhum registro de vacina encontrado.",
    healthTip: "Dica: Mantenha a carteirinha de vacinação atualizada para acessar hotéis e creches.",
    planDescBasic: "Acesso ao Perfil e Adoção",
    planDescStart: "Vacinas, Agendamentos e Recursos Básicos",
    planDescPremium: "Acesso Total, Namoro, IA e Suporte Prioritário",
    availableForDatingLabel: "Disponível para Namoro/Cruza",
    datingPlanWarning: "Recurso exclusivo para plano Premium!",
    featureLocked: "Funcionalidade Bloqueada",
    upgradeToAccess: "Faça upgrade do seu plano para acessar este recurso.",
    unlockNow: "Desbloquear Agora",
    tooltipProfile: "Gerencie as informações e fotos do seu pet.",
    tooltipAdoption: "Encontre um novo amigo ou adote.",
    tooltipDating: "Encontre o par perfeito para seu pet.",
    tooltipHealth: "Controle de vacinas e saúde.",
    tooltipServices: "Agende veterinários, banho e tosa.",
    reqPlanBasic: "Plano Basic ou superior",
    reqPlanStart: "Requer Plano Start",
    reqPlanPremium: "Requer Plano Premium",
    landingAdoptionTitle: "Encontre seu novo melhor amigo",
    landingAdoptionSubtitle: "Centenas de pets estão esperando por um lar cheio de amor. Faça a diferença hoje.",
    landingAdoptionBtn: "Ver Pets para Adoção",
    publicAdoptionTitle: "Adoção Responsável",
    publicAdoptionSubtitle: "Estes amigos estão procurando um lar. Navegue, apaixone-se e entre em contato.",
    backToHome: "Voltar ao Início",
    interestBtn: "Tenho Interesse",
    locationLabel: "Localização",
    getLocationBtn: "Atualizar com GPS",
    locationError: "Erro ao obter localização. Verifique as permissões.",
    kmAway: "km de distância",
    locationUpdated: "Localização atualizada com sucesso!",
    selectedPlanLabel: "Plano Selecionado",
    passwordStrength: "Força da senha",
    weak: "Fraca",
    medium: "Média",
    strong: "Forte",
    acceptTerms: "Li e concordo com os",
    termsLink: "Termos de Uso",
    privacyLink: "Política de Privacidade",
    termsError: "Você precisa aceitar os termos para continuar.",
    termsTitle: "Termos de Uso",
    privacyTitle: "Política de Privacidade",
    emailError: "Por favor, insira um e-mail válido.",
    myFavorites: "Meus Favoritos",
    noFavorites: "Você ainda não favoritou nenhum pet para adoção.",
    footerRights: "Todos os direitos reservados",
    footerCompany: "Empresa",
    footerLegal: "Legal",
    footerAbout: "Sobre Nós",
    footerContact: "Contato",
    footerFollowUs: "Siga-nos",
    footerBlog: "Blog",
    footerCareers: "Carreiras",
    footerHelp: "Central de Ajuda",
    searchLocationPlaceholder: "Buscar por CEP ou Cidade",
    searchBtn: "Buscar",
    locationNotFound: "Localização não encontrada. Usando localização padrão.",
    filterAll: "Todos",
    filterType: "Filtrar por tipo",
    minRating: "Avaliação Mín.",
    clearFilters: "Limpar Filtros",
    detecting: "Detectando...",
    setLocation: "Definir Local",
    headerLanguage: "Idioma",
    headerLocation: "Você está em:",
    ongSectionTitle: "Apoie ONGs Locais",
    ongSectionSubtitle: "Sua ONG ajuda animais? Junte-se à nossa plataforma para divulgar animais para adoção e receber apoio da comunidade.",
    ongBtn: "Cadastrar Minha ONG",
    ongFormTitle: "Cadastro de ONG",
    ongFormDesc: "Preencha os dados abaixo para registrar sua organização e ajudar mais animais.",
    ongName: "Nome da ONG",
    ongCnpj: "CNPJ",
    ongDescription: "Descrição da Organização",
    ongRegisterSuccess: "Cadastro realizado com sucesso! Em breve entraremos em contato.",
    viewOngsBtn: "Ver ONGs cadastradas"
  },
  [Language.EN]: {
    heroTitle: "Your Pet's World in One Place",
    heroSubtitle: "Connect, care, and love. The complete platform for your best friend.",
    ctaStart: "Get Started",
    ctaLogin: "Login",
    planBasic: "AnyBasic",
    planStart: "AnyStart",
    planPremium: "AnyPremium",
    perMonth: "/month",
    features: "Features",
    loginTitle: "Access Account",
    email: "Email",
    password: "Password",
    loginButton: "Enter Platform",
    dashHome: "Home",
    dashAdoption: "Adoption",
    dashDating: "Dating",
    dashHealth: "Health Card",
    dashServices: "Services",
    dashProfile: "Pet Profile",
    logout: "Logout",
    welcome: "Welcome back",
    myPets: "My Pets",
    vaccines: "Vaccines",
    serviceVet: "Vets",
    serviceGroom: "Grooming",
    serviceHotel: "Hotels",
    serviceWalker: "Dog Walkers",
    bookNow: "Book Now",
    adoptMe: "Adopt Me",
    match: "Match",
    generateBio: "Generate Bio with AI",
    bioPlaceholder: "Write about your pet...",
    priceFree: "Free",
    priceStart: "$9.90",
    pricePremium: "$19.90",
    popular: "POPULAR",
    featProfile: "Pet Profile",
    featAdoption: "Adoption Access",
    featBasic: "Everything in Basic",
    featVaccines: "Vaccination Card",
    featScheduling: "Service Scheduling",
    featStart: "Everything in Start",
    featDating: "Dating / Breeding",
    featAIBio: "AI Bio Generator",
    featSupport: "Priority Support",
    btnChooseBasic: "Choose Basic",
    btnChooseStart: "Choose Start",
    btnChoosePremium: "Choose Premium",
    signupTitle: "Create Account",
    name: "Full Name",
    confirmPassword: "Confirm Password",
    signupButton: "Sign Up",
    haveAccount: "Already have an account? Login",
    noAccount: "Don't have an account? Sign Up",
    createAccount: "Create Account",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    weight: "Weight (kg)",
    photoUrl: "Photo URL",
    ageLabel: "Age (years)",
    breedLabel: "Breed",
    changePhoto: "Change Photo",
    userProfile: "Owner Details",
    switchPet: "Switch Pet",
    addNewPet: "Add New Pet",
    noPets: "No pets found",
    createFirstPet: "Register your first pet",
    userSettings: "My Account",
    phone: "Phone",
    petName: "Pet Name",
    petType: "Animal Type",
    selectPet: "Select a Pet",
    deletePet: "Delete Pet",
    confirmDeletePet: "Are you sure you want to delete this pet? This action cannot be undone.",
    deletePetWarning: "Permanently delete this profile",
    currentPlan: "Current Plan",
    upgradePlan: "Change Plan",
    planBenefits: "Your plan benefits",
    managePlan: "Manage Subscription",
    typeDog: "Dog",
    typeCat: "Cat",
    typeBird: "Bird",
    typeOther: "Other",
    healthVaccine: "Vaccine",
    healthDate: "Date Given",
    healthNextDue: "Next Due",
    healthStatus: "Status",
    healthNoRecords: "No vaccine records found.",
    healthTip: "Tip: Keep your vaccination card updated to access Pet Hotels and Daycare services.",
    planDescBasic: "Profile & Adoption Access",
    planDescStart: "Vaccines, Scheduling, Basic Features",
    planDescPremium: "Full Access, Dating, AI, Priority Support",
    availableForDatingLabel: "Available for Dating/Breeding",
    datingPlanWarning: "This is a Premium plan feature!",
    featureLocked: "Feature Locked",
    upgradeToAccess: "Upgrade your plan to access this feature.",
    unlockNow: "Unlock Now",
    tooltipProfile: "Manage your pet's information and photos.",
    tooltipAdoption: "Find a new friend or adopt.",
    tooltipDating: "Find the perfect match for your pet.",
    tooltipHealth: "Track vaccines and health records.",
    tooltipServices: "Book vets, grooming, and more.",
    reqPlanBasic: "Basic Plan or higher",
    reqPlanStart: "Requires Start Plan",
    reqPlanPremium: "Requires Premium Plan",
    landingAdoptionTitle: "Find Your New Best Friend",
    landingAdoptionSubtitle: "Hundreds of pets are waiting for a loving home. Make a difference today.",
    landingAdoptionBtn: "View Pets for Adoption",
    publicAdoptionTitle: "Responsible Adoption",
    publicAdoptionSubtitle: "These friends are looking for a home. Browse, fall in love, and get in touch.",
    backToHome: "Back to Home",
    interestBtn: "I'm Interested",
    locationLabel: "Location",
    getLocationBtn: "Update with GPS",
    locationError: "Error getting location. Check permissions.",
    kmAway: "km away",
    locationUpdated: "Location updated successfully!",
    selectedPlanLabel: "Selected Plan",
    passwordStrength: "Password Strength",
    weak: "Weak",
    medium: "Medium",
    strong: "Strong",
    acceptTerms: "I read and accept the",
    termsLink: "Terms of Service",
    privacyLink: "Privacy Policy",
    termsError: "You must accept the terms to continue.",
    termsTitle: "Terms of Service",
    privacyTitle: "Privacy Policy",
    emailError: "Please enter a valid email.",
    myFavorites: "My Favorites",
    noFavorites: "You haven't favorited any pets for adoption yet.",
    footerRights: "All rights reserved",
    footerCompany: "Company",
    footerLegal: "Legal",
    footerAbout: "About Us",
    footerContact: "Contact",
    footerFollowUs: "Follow Us",
    footerBlog: "Blog",
    footerCareers: "Careers",
    footerHelp: "Help Center",
    searchLocationPlaceholder: "Search by Zip or City",
    searchBtn: "Search",
    locationNotFound: "Location not found. Using default location.",
    filterAll: "All",
    filterType: "Filter by type",
    minRating: "Min. Rating",
    clearFilters: "Clear Filters",
    detecting: "Detecting...",
    setLocation: "Set Location",
    headerLanguage: "Language",
    headerLocation: "You are at:",
    ongSectionTitle: "Support Local NGOs",
    ongSectionSubtitle: "Does your NGO help animals? Join our platform to promote adoptable pets and receive community support.",
    ongBtn: "Register My NGO",
    ongFormTitle: "NGO Registration",
    ongFormDesc: "Fill in the details below to register your organization and help more animals.",
    ongName: "NGO Name",
    ongCnpj: "Tax ID (CNPJ)",
    ongDescription: "Organization Description",
    ongRegisterSuccess: "Registration successful! We will contact you soon.",
    viewOngsBtn: "View Registered NGOs"
  },
  [Language.ES]: {
    heroTitle: "El Mundo de tu Mascota en un Solo Lugar",
    heroSubtitle: "Conecta, cuida y ama. La plataforma completa para tu mejor amigo.",
    ctaStart: "Empezar Ahora",
    ctaLogin: "Ingresar",
    planBasic: "AnyBasic",
    planStart: "AnyStart",
    planPremium: "AnyPremium",
    perMonth: "/mes",
    features: "Características",
    loginTitle: "Acceso",
    email: "Correo",
    password: "Clave",
    loginButton: "Entrar a la Plataforma",
    dashHome: "Inicio",
    dashAdoption: "Adopción",
    dashDating: "Citas",
    dashHealth: "Cartilla",
    dashServices: "Servicios",
    dashProfile: "Perfil de Mascota",
    logout: "Salir",
    welcome: "Bienvenido de nuevo",
    myPets: "Mis Mascotas",
    vaccines: "Vacunas",
    serviceVet: "Veterinarios",
    serviceGroom: "Peluquería",
    serviceHotel: "Hoteles",
    serviceWalker: "Paseadores",
    bookNow: "Reservar",
    adoptMe: "Adóptame",
    match: "Coincidir",
    generateBio: "Generar Bio con IA",
    bioPlaceholder: "Escribe sobre tu mascota...",
    priceFree: "Gratis",
    priceStart: "$9.90",
    pricePremium: "$19.90",
    popular: "POPULAR",
    featProfile: "Perfil de Mascota",
    featAdoption: "Acceso a Adopción",
    featBasic: "Todo lo de Basic",
    featVaccines: "Cartilla de Vacunación",
    featScheduling: "Reserva de Servicios",
    featStart: "Todo lo de Start",
    featDating: "Citas / Cría",
    featAIBio: "Generador de Bio IA",
    featSupport: "Soporte Prioritario",
    btnChooseBasic: "Elegir Basic",
    btnChooseStart: "Elegir Start",
    btnChoosePremium: "Elegir Premium",
    signupTitle: "Crear Cuenta",
    name: "Nombre Completo",
    confirmPassword: "Confirmar Clave",
    signupButton: "Registrarse",
    haveAccount: "¿Ya tienes cuenta? Ingresar",
    noAccount: "¿No tienes cuenta? Regístrate",
    createAccount: "Crear Cuenta",
    editProfile: "Editar Perfil",
    saveChanges: "Guardar Cambios",
    cancel: "Cancelar",
    weight: "Peso (kg)",
    photoUrl: "URL de Foto",
    ageLabel: "Edad (años)",
    breedLabel: "Raza",
    changePhoto: "Cambiar Foto",
    userProfile: "Datos del Dueño",
    switchPet: "Cambiar Mascota",
    addNewPet: "Agregar Nueva Mascota",
    noPets: "No se encontraron mascotas",
    createFirstPet: "Registra tu primera mascota",
    userSettings: "Mi Cuenta",
    phone: "Teléfono",
    petName: "Nombre de Mascota",
    petType: "Tipo de Animal",
    selectPet: "Selecciona una Mascota",
    deletePet: "Eliminar Mascota",
    confirmDeletePet: "¿Estás seguro de que deseas eliminar esta mascota? Esta acción no se puede deshacer.",
    deletePetWarning: "Eliminar permanentemente este perfil",
    currentPlan: "Plan Actual",
    upgradePlan: "Cambiar Plan",
    planBenefits: "Beneficios de tu plan",
    managePlan: "Gestionar Suscripción",
    typeDog: "Perro",
    typeCat: "Gato",
    typeBird: "Pájaro",
    typeOther: "Otro",
    healthVaccine: "Vacuna",
    healthDate: "Fecha de Aplicación",
    healthNextDue: "Próxima Dosis",
    healthStatus: "Estado",
    healthNoRecords: "No se encontraron registros de vacunas.",
    healthTip: "Consejo: Mantén la cartilla de vacunación actualizada para acceder a hoteles y guarderías.",
    planDescBasic: "Acceso a Perfil y Adopción",
    planDescStart: "Vacunas, Reservas y Funciones Básicas",
    planDescPremium: "Acceso Total, Citas, IA y Soporte",
    availableForDatingLabel: "Disponible para Citas/Cría",
    datingPlanWarning: "¡Función exclusiva del plan Premium!",
    featureLocked: "Función Bloqueada",
    upgradeToAccess: "Mejora tu plan para acceder a esta función.",
    unlockNow: "Desbloquear Agora",
    tooltipProfile: "Gestiona la información y fotos de tu mascota.",
    tooltipAdoption: "Encuentra un nuevo amigo o adopta.",
    tooltipDating: "Encuentra la pareja perfecta para tu mascota.",
    tooltipHealth: "Seguimiento de vacunas y salud.",
    tooltipServices: "Reserva veterinarios, peluquería y más.",
    reqPlanBasic: "Plan Basic o superior",
    reqPlanStart: "Requiere Plan Start",
    reqPlanPremium: "Requiere Plan Premium",
    landingAdoptionTitle: "Encuentra tu nuevo mejor amigo",
    landingAdoptionSubtitle: "Cientos de mascotas esperan un hogar lleno de amor. Haz la diferencia hoy.",
    landingAdoptionBtn: "Ver Mascotas en Adopción",
    publicAdoptionTitle: "Adopción Responsable",
    publicAdoptionSubtitle: "Estos amigos buscan un hogar. Navega, enamórate y contáctanos.",
    backToHome: "Volver al Inicio",
    interestBtn: "Me Interesa",
    locationLabel: "Ubicación",
    getLocationBtn: "Actualizar con GPS",
    locationError: "Error al obtener ubicación. Revisa permisos.",
    kmAway: "km de distancia",
    locationUpdated: "¡Ubicación actualizada con éxito!",
    selectedPlanLabel: "Plan Seleccionado",
    passwordStrength: "Seguridad de clave",
    weak: "Débil",
    medium: "Media",
    strong: "Fuerte",
    acceptTerms: "Leí y acepto los",
    termsLink: "Términos de Uso",
    privacyLink: "Política de Privacidade",
    termsError: "Debes aceptar los términos para continuar.",
    termsTitle: "Términos de Uso",
    privacyTitle: "Política de Privacidad",
    emailError: "Por favor, introduzca un correo electrónico válido.",
    myFavorites: "Mis Favoritos",
    noFavorites: "Aún no has marcado ninguna mascota como favorita.",
    footerRights: "Todos los derechos reservados",
    footerCompany: "Empresa",
    footerLegal: "Legal",
    footerAbout: "Sobre Nosotros",
    footerContact: "Contacto",
    footerFollowUs: "Síguenos",
    footerBlog: "Blog",
    footerCareers: "Carreras",
    footerHelp: "Centro de Ayuda",
    searchLocationPlaceholder: "Buscar por Código Postal o Ciudad",
    searchBtn: "Buscar",
    locationNotFound: "Ubicación no encontrada. Usando ubicación predeterminada.",
    filterAll: "Todos",
    filterType: "Filtrar por tipo",
    minRating: "Valoración Mín.",
    clearFilters: "Limpiar Filtros",
    detecting: "Detectando...",
    setLocation: "Establecer Ubicación",
    headerLanguage: "Idioma",
    headerLocation: "Estás en:",
    ongSectionTitle: "Apoya a las ONG Locales",
    ongSectionSubtitle: "¿Tu ONG ayuda animales? Únete a nuestra plataforma para promover mascotas adoptables y recibir apoyo.",
    ongBtn: "Registrar mi ONG",
    ongFormTitle: "Registro de ONG",
    ongFormDesc: "Complete los detalles a continuación para registrar su organización y ayudar a más animales.",
    ongName: "Nombre de la ONG",
    ongCnpj: "RUC / ID Fiscal",
    ongDescription: "Descripción de la Organización",
    ongRegisterSuccess: "¡Registro exitoso! Nos pondremos en contacto pronto.",
    viewOngsBtn: "Ver ONG registradas"
  }
};

// Base location: São Paulo (-23.5505, -46.6333) for mock data
export const MOCK_ADOPTION_PETS: Pet[] = [
  { id: '1', name: 'Thor', breed: 'Golden Retriever', age: 2, type: 'dog', image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=400&q=80', bio: 'Friendly and energetic.', location: { lat: -23.5605, lng: -46.6433 } }, // Near Paulista
  { id: '2', name: 'Luna', breed: 'Siamese', age: 1, type: 'cat', image: 'https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&w=400&q=80', bio: 'Quiet and loving.', location: { lat: -23.5405, lng: -46.6233 } },
  { id: '3', name: 'Bob', breed: 'Bulldog', age: 4, type: 'dog', image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=400&q=80', bio: 'Loves sleeping.', location: { lat: -23.5705, lng: -46.6533 } },
];

export const MOCK_DATING_PETS: Pet[] = [
  { id: '4', name: 'Bella', breed: 'Poodle', age: 3, type: 'dog', image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=400&q=80', bio: 'Looking for a playdate.', location: { lat: -23.5555, lng: -46.6355 } },
  { id: '5', name: 'Max', breed: 'German Shepherd', age: 3, type: 'dog', image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?auto=format&fit=crop&w=400&q=80', bio: 'Very active and protective.', location: { lat: -23.5805, lng: -46.6133 } },
];

export const MOCK_SERVICES: ServiceProvider[] = [
  { id: '1', name: 'Dr. Dolittle Clinic', type: 'veterinarian', rating: 4.8, image: 'https://picsum.photos/200/200?random=10', location: { lat: -23.5615, lng: -46.6559 }, address: 'Av. Paulista, 1000' },
  { id: '2', name: 'Happy Paws Grooming', type: 'petshop', rating: 4.5, image: 'https://picsum.photos/200/200?random=11', location: { lat: -23.5505, lng: -46.6333 }, address: 'Centro Histórico' },
  { id: '3', name: 'Walkies with Sarah', type: 'dogwalker', rating: 5.0, image: 'https://picsum.photos/200/200?random=12', location: { lat: -23.5905, lng: -46.6733 }, address: 'Vila Olímpia' },
  { id: '4', name: 'Pet Paradise Hotel', type: 'hotel', rating: 4.7, image: 'https://picsum.photos/200/200?random=13', location: { lat: -23.5205, lng: -46.6033 }, address: 'Santana' },
];

export const MOCK_DAILY_PHOTOS = [
  { url: 'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?q=80&w=1000&auto=format&fit=crop', petName: 'Rex', breed: 'Golden Retriever', location: 'São Paulo, SP' },
  { url: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?q=80&w=1000&auto=format&fit=crop', petName: 'Mia', breed: 'Persa', location: 'Rio de Janeiro, RJ' },
  { url: 'https://images.unsplash.com/photo-1453227588063-bb302b62f50b?q=80&w=1000&auto=format&fit=crop', petName: 'Buddy', breed: 'Bulldog Francês', location: 'Curitiba, PR' },
  { url: 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?q=80&w=1000&auto=format&fit=crop', petName: 'Thor', breed: 'Husky Siberiano', location: 'Belo Horizonte, MG' },
];
