

import { Language, Pet, ServiceProvider, TranslationKey, Ong } from './types';

export const TRANSLATIONS: Record<Language, Record<TranslationKey, string>> = {
  [Language.PT]: {
    heroTitle: "O Mundo do Seu Pet em Um Só Lugar",
    heroSubtitle: "Conecte-se, cuide e ame. A plataforma completa para o seu melhor amigo.",
    ctaStart: "Começar Agora",
    ctaLogin: "Entrar",
    planBasic: "AnyBasic",
    planStart: "AnyStart",
    planPremium: "AnyPremium",
    perMonth: "/mês",
    features: "Recursos",
    loginTitle: "Acesse sua Conta",
    email: "E-mail",
    password: "Senha",
    loginButton: "Entrar na Plataforma",
    dashHome: "Início",
    dashAdoption: "Adoção",
    dashDating: "Namoro",
    dashHealth: "Carteirinha",
    dashServices: "Agendamentos",
    dashProfile: "Perfil do Pet",
    dashLostFound: "Achados e Perdidos",
    dashMyOngs: "Minhas ONGs",
    logout: "Sair",
    welcome: "Bem-vindo de volta",
    myPets: "Meus Pets",
    vaccines: "Vacinas",
    serviceVet: "Veterinários",
    serviceGroom: "Petshops",
    serviceHotel: "Hotéis",
    serviceWalker: "Dog Walkers",
    bookNow: "Agendar",
    adoptMe: "Me Adote",
    match: "Dar Match",
    generateBio: "Gerar Bio com IA",
    bioPlaceholder: "Escreva sobre seu pet...",
    priceFree: "Grátis",
    priceStart: "R$ 29,90",
    pricePremium: "R$ 59,90",
    popular: "POPULAR",
    featProfile: "Perfil do Pet",
    featAdoption: "Acesso à Adoção",
    featBasic: "Tudo do Basic",
    featVaccines: "Carteira de Vacinação Digital",
    featScheduling: "Agendamento de Serviços",
    featStart: "Tudo do Start",
    featDating: "Namoro / Cruzamento",
    featAIBio: "Gerador de Bio com IA",
    featSupport: "Suporte Prioritário",
    featLostFound: "Achados e Perdidos",
    featOngRegister: "Cadastro de ONGs",
    btnChooseBasic: "Escolher Basic",
    btnChooseStart: "Escolher Start",
    btnChoosePremium: "Escolher Premium",
    signupTitle: "Crie sua Conta",
    name: "Nome Completo",
    confirmPassword: "Confirmar Senha",
    signupButton: "Cadastrar",
    haveAccount: "Já tem uma conta? Entrar",
    noAccount: "Não tem uma conta? Cadastre-se",
    createAccount: "Criar Conta",
    editProfile: "Editar Perfil",
    saveChanges: "Salvar Alterações",
    cancel: "Cancelar",
    weight: "Peso (kg)",
    photoUrl: "URL da Foto",
    ageLabel: "Idade (anos)",
    breedLabel: "Raça",
    changePhoto: "Alterar Foto",
    userProfile: "Dados do Dono",
    switchPet: "Trocar Pet",
    addNewPet: "Adicionar Novo Pet",
    noPets: "Nenhum pet encontrado",
    createFirstPet: "Cadastre seu primeiro pet",
    userSettings: "Minha Conta",
    phone: "Telefone",
    petName: "Nome do Pet",
    petType: "Tipo de Animal",
    selectPet: "Selecione um Pet",
    deletePet: "Excluir Pet",
    confirmDeletePet: "Tem certeza que deseja excluir este pet? Essa ação não pode ser desfeita.",
    deletePetWarning: "Excluir este perfil permanentemente",
    currentPlan: "Plano Atual",
    upgradePlan: "Alterar Plano",
    planBenefits: "Benefícios do seu plano",
    managePlan: "Gerenciar Assinatura",
    typeDog: "Cachorro",
    typeCat: "Gato",
    typeBird: "Pássaro",
    typeOther: "Outro",
    healthVaccine: "Vacina",
    healthDate: "Data da Aplicação",
    healthNextDue: "Próxima Dose",
    healthStatus: "Status",
    healthNoRecords: "Nenhum registro de vacina encontrado.",
    healthTip: "Dica: Mantenha a carteirinha de vacinação atualizada para acessar hotéis e creches.",
    planDescBasic: "Perfil, Adoção, ONGs e Achados e Perdidos",
    planDescStart: "Vacinas, Agendamentos e Recursos Básicos",
    planDescPremium: "Acesso Total, Namoro, IA e Suporte Prioritário",
    availableForDatingLabel: "Disponível para Namoro/Cruza",
    datingPlanWarning: "Recurso exclusivo para plano Premium!",
    featureLocked: "Funcionalidade Bloqueada",
    upgradeToAccess: "Faça upgrade do seu plano para acessar este recurso.",
    unlockNow: "Desbloquear Agora",
    tooltipProfile: "Gerencie as informações e fotos do seu pet.",
    tooltipAdoption: "Encontre um novo amigo ou adote.",
    tooltipDating: "Encontre o par perfeito para seu pet.",
    tooltipHealth: "Controle de vacinas e saúde.",
    tooltipServices: "Agende veterinários, banho e tosa.",
    reqPlanBasic: "Plano Basic ou superior",
    reqPlanStart: "Requer Plano Start",
    reqPlanPremium: "Requer Plano Premium",
    landingAdoptionTitle: "Encontre seu novo melhor amigo",
    landingAdoptionSubtitle: "Centenas de pets estão esperando por um lar cheio de amor. Faça a diferença hoje.",
    landingAdoptionBtn: "Ver Pets para Adoção",
    publicAdoptionTitle: "Adoção Responsável",
    publicAdoptionSubtitle: "Estes amigos estão procurando um lar. Navegue, apaixone-se e entre em contato.",
    backToHome: "Voltar ao Início",
    interestBtn: "Tenho Interesse",
    locationLabel: "Localização",
    getLocationBtn: "Atualizar com GPS",
    locationError: "Erro ao obter localização. Verifique as permissões.",
    kmAway: "km de distância",
    locationUpdated: "Localização atualizada com sucesso!",
    selectedPlanLabel: "Plano Selecionado",
    passwordStrength: "Força da senha",
    weak: "Fraca",
    medium: "Média",
    strong: "Forte",
    acceptTerms: "Li e concordo com os",
    termsLink: "Termos de Uso",
    privacyLink: "Política de Privacidade",
    termsError: "Você precisa aceitar os termos para continuar.",
    termsTitle: "Termos de Uso",
    privacyTitle: "Política de Privacidade",
    emailError: "Por favor, insira um e-mail válido.",
    myFavorites: "Meus Favoritos",
    noFavorites: "Você ainda não favoritou nenhum pet para adoção.",
    footerRights: "Todos os direitos reservados",
    footerCompany: "Empresa",
    footerLegal: "Legal",
    footerAbout: "Sobre Nós",
    footerContact: "Contato",
    footerFollowUs: "Siga-nos",
    footerBlog: "Blog",
    footerCareers: "Carreiras",
    footerHelp: "Central de Ajuda",
    searchLocationPlaceholder: "Buscar por CEP ou Cidade",
    searchBtn: "Buscar",
    locationNotFound: "Localização não encontrada. Usando localização padrão.",
    filterAll: "Todos",
    filterType: "Filtrar por tipo",
    minRating: "Avaliação Mín.",
    clearFilters: "Limpar Filtros",
    detecting: "Detectando...",
    setLocation: "Definir Local",
    headerLanguage: "Idioma",
    headerLocation: "Você está em:",
    ongSectionTitle: "Apoie ONGs Locais",
    ongSectionSubtitle: "Sua ONG ajuda animais? Junte-se à nossa plataforma para divulgar animais para adoção e receber apoio da comunidade.",
    ongBtn: "Cadastrar Minha ONG",
    ongFormTitle: "Cadastro de ONG",
    ongFormDesc: "Preencha os dados abaixo para registrar sua organização e ajudar mais animais.",
    ongName: "Nome da ONG",
    ongCnpj: "CNPJ",
    ongDescription: "Descrição da Organização",
    ongRegisterSuccess: "Cadastro realizado com sucesso! Em breve entraremos em contato.",
    viewOngsBtn: "Ver ONGs cadastradas",
    invalidCnpj: "CNPJ inválido. Verifique o número digitado.",
    invalidTaxId: "Número de registro inválido.",
    registeredOngsTitle: "ONGs Parceiras",
    seeAllOngs: "Ver todas as ONGs",
    partnerOngs: "ONGs Parceiras",
    searchOngsPlaceholder: "Buscar ONGs por cidade, estado ou nome",
    noOngsFound: "Nenhuma ONG encontrada com esses critérios.",
    viewOng: "Ver ONG",
    aboutOng: "Sobre a ONG",
    contactOng: "Contato",
    availablePets: "Pets para Adoção",
    donateBtn: "Fazer Doação",
    copyPix: "Copiar Chave Pix",
    pixCopied: "Chave Pix copiada!",
    bankDetails: "Dados Bancários",
    bankName: "Banco",
    agency: "Agência",
    account: "Conta",
    prevPage: "Anterior",
    nextPage: "Próxima",
    pageOf: "de",
    watchVideo: "Assistir Vídeo",
    pauseVideo: "Pausar Vídeo",
    verifyLocationBtn: "Verificar Local",
    locationMatch: "Localização verificada! Você está no local do perfil.",
    locationMismatch: "Atenção: Sua localização atual difere do perfil.",
    verifying: "Verificando...",
    lostFoundTitle: "Achados e Perdidos",
    lostFoundSubtitle: "Ajude a reunir pets perdidos com seus donos.",
    reportLost: "Reportar Pet Perdido",
    reportFound: "Reportar Pet Encontrado",
    noLostPets: "Nenhum pet desaparecido reportado na sua região.",
    myOngsTitle: "Minhas ONGs Cadastradas",
    noMyOngs: "Você ainda não cadastrou nenhuma ONG.",
    landingLostFoundTitle: "Perdeu ou encontrou um pet?",
    landingLostFoundSubtitle: "Nossa comunidade pode ajudar! Utilize nossa ferramenta de Achados e Perdidos baseada em geolocalização para reencontrar pets.",
    landingLostFoundBtn: "Acessar Achados e Perdidos",
    linkCopied: "Link copiado!",
    viewMap: "Ver Mapa",
    viewList: "Ver Lista",
    adoptionSuccessTitle: "Interesse Registrado!",
    adoptionSuccessMsg: "Seu contato foi enviado para a ONG/Responsável. Em breve eles entrarão em contato com você.",
    tabOverview: "Visão Geral",
    tabTransparency: "Portal da Transparência",
    totalRaised: "Total Arrecadado (Mês)",
    totalExpenses: "Despesas Totais",
    activeDonors: "Doadores Ativos",
    monthlyBreakdown: "Detalhamento de Custos",
    expenseFood: "Ração e Alimentos",
    expenseVet: "Veterinário e Exames",
    expenseMaintenance: "Manutenção do Abrigo",
    expenseMeds: "Medicamentos",
    howToHelpTitle: "Outras Formas de Ajudar",
    helpTip1: "Seja um voluntário para passear com os cães",
    helpTip2: "Doe materiais de limpeza ou ração",
    helpTip3: "Compartilhe nossos pets nas redes sociais",
    locationMap: "Localização",
    invalidFileType: "Tipo de arquivo inválido. Apenas imagens são permitidas.",
    fileTooLarge: "Arquivo muito grande. O tamanho máximo é 5MB.",
    scheduleTitle: "Agendar Serviço",
    selectDate: "Selecione a Data",
    selectTime: "Selecione o Horário",
    confirmBooking: "Confirmar Agendamento",
    bookingSuccess: "Agendamento realizado com sucesso!",
    landingServicesTitle: "Cuidamos de tudo para você",
    landingServicesSubtitle: "Encontre os melhores serviços para o seu pet, agende com facilidade e aproveite descontos exclusivos.",
    landingServicesBtn: "Conhecer Planos",
    landingDatingTitle: "O Amor está no Ar",
    landingDatingSubtitle: "Encontre o par perfeito para seu pet. Com o AnyPremium, você pode encontrar parceiros baseados em raça, idade e localização para namoro ou cruzamento.",
    landingDatingBtn: "Conhecer Plano Premium"
  },
  [Language.EN]: {
    heroTitle: "Your Pet's World in One Place",
    heroSubtitle: "Connect, care, and love. The complete platform for your best friend.",
    ctaStart: "Get Started",
    ctaLogin: "Login",
    planBasic: "AnyBasic",
    planStart: "AnyStart",
    planPremium: "AnyPremium",
    perMonth: "/month",
    features: "Features",
    loginTitle: "Access Account",
    email: "Email",
    password: "Password",
    loginButton: "Enter Platform",
    dashHome: "Home",
    dashAdoption: "Adoption",
    dashDating: "Dating",
    dashHealth: "Health Card",
    dashServices: "Services",
    dashProfile: "Pet Profile",
    dashLostFound: "Lost & Found",
    dashMyOngs: "My NGOs",
    logout: "Logout",
    welcome: "Welcome back",
    myPets: "My Pets",
    vaccines: "Vaccines",
    serviceVet: "Vets",
    serviceGroom: "Grooming",
    serviceHotel: "Hotels",
    serviceWalker: "Dog Walkers",
    bookNow: "Book Now",
    adoptMe: "Adopt Me",
    match: "Match",
    generateBio: "Generate Bio with AI",
    bioPlaceholder: "Write about your pet...",
    priceFree: "Free",
    priceStart: "$9.90",
    pricePremium: "$19.90",
    popular: "POPULAR",
    featProfile: "Pet Profile",
    featAdoption: "Adoption Access",
    featBasic: "Everything in Basic",
    featVaccines: "Vaccination Card",
    featScheduling: "Service Scheduling",
    featStart: "Everything in Start",
    featDating: "Dating / Breeding",
    featAIBio: "AI Bio Generator",
    featSupport: "Priority Support",
    featLostFound: "Lost & Found",
    featOngRegister: "Register NGOs",
    btnChooseBasic: "Choose Basic",
    btnChooseStart: "Choose Start",
    btnChoosePremium: "Choose Premium",
    signupTitle: "Create Account",
    name: "Full Name",
    confirmPassword: "Confirm Password",
    signupButton: "Sign Up",
    haveAccount: "Already have an account? Login",
    noAccount: "Don't have an account? Sign Up",
    createAccount: "Create Account",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    weight: "Weight (kg)",
    photoUrl: "Photo URL",
    ageLabel: "Age (years)",
    breedLabel: "Breed",
    changePhoto: "Change Photo",
    userProfile: "Owner Details",
    switchPet: "Switch Pet",
    addNewPet: "Add New Pet",
    noPets: "No pets found",
    createFirstPet: "Register your first pet",
    userSettings: "My Account",
    phone: "Phone",
    petName: "Pet Name",
    petType: "Animal Type",
    selectPet: "Select a Pet",
    deletePet: "Delete Pet",
    confirmDeletePet: "Are you sure you want to delete this pet? This action cannot be undone.",
    deletePetWarning: "Permanently delete this profile",
    currentPlan: "Current Plan",
    upgradePlan: "Change Plan",
    planBenefits: "Your plan benefits",
    managePlan: "Manage Subscription",
    typeDog: "Dog",
    typeCat: "Cat",
    typeBird: "Bird",
    typeOther: "Other",
    healthVaccine: "Vaccine",
    healthDate: "Date Given",
    healthNextDue: "Next Due",
    healthStatus: "Status",
    healthNoRecords: "No vaccine records found.",
    healthTip: "Tip: Keep your vaccination card updated to access Pet Hotels and Daycare services.",
    planDescBasic: "Profile, Adoption, NGOs & Lost/Found",
    planDescStart: "Vaccines, Scheduling, Basic Features",
    planDescPremium: "Full Access, Dating, AI, Priority Support",
    availableForDatingLabel: "Available for Dating/Breeding",
    datingPlanWarning: "This is a Premium plan feature!",
    featureLocked: "Feature Locked",
    upgradeToAccess: "Upgrade your plan to access this feature.",
    unlockNow: "Unlock Now",
    tooltipProfile: "Manage your pet's information and photos.",
    tooltipAdoption: "Find a new friend or adopt.",
    tooltipDating: "Find the perfect match for your pet.",
    tooltipHealth: "Track vaccines and health records.",
    tooltipServices: "Book vets, grooming, and more.",
    reqPlanBasic: "Basic Plan or higher",
    reqPlanStart: "Requires Start Plan",
    reqPlanPremium: "Requires Premium Plan",
    landingAdoptionTitle: "Find Your New Best Friend",
    landingAdoptionSubtitle: "Hundreds of pets are waiting for a loving home. Make a difference today.",
    landingAdoptionBtn: "View Pets for Adoption",
    publicAdoptionTitle: "Responsible Adoption",
    publicAdoptionSubtitle: "These friends are looking for a home. Browse, fall in love, and get in touch.",
    backToHome: "Back to Home",
    interestBtn: "I'm Interested",
    locationLabel: "Location",
    getLocationBtn: "Update with GPS",
    locationError: "Error getting location. Check permissions.",
    kmAway: "km away",
    locationUpdated: "Location updated successfully!",
    selectedPlanLabel: "Selected Plan",
    passwordStrength: "Password Strength",
    weak: "Weak",
    medium: "Medium",
    strong: "Strong",
    acceptTerms: "I read and accept the",
    termsLink: "Terms of Service",
    privacyLink: "Privacy Policy",
    termsError: "You must accept the terms to continue.",
    termsTitle: "Terms of Service",
    privacyTitle: "Privacy Policy",
    emailError: "Please enter a valid email.",
    myFavorites: "My Favorites",
    noFavorites: "You haven't favorited any pets for adoption yet.",
    footerRights: "All rights reserved",
    footerCompany: "Company",
    footerLegal: "Legal",
    footerAbout: "About Us",
    footerContact: "Contact",
    footerFollowUs: "Follow Us",
    footerBlog: "Blog",
    footerCareers: "Careers",
    footerHelp: "Help Center",
    searchLocationPlaceholder: "Search by Zip or City",
    searchBtn: "Search",
    locationNotFound: "Location not found. Using default location.",
    filterAll: "All",
    filterType: "Filter by type",
    minRating: "Min. Rating",
    clearFilters: "Clear Filters",
    detecting: "Detecting...",
    setLocation: "Set Location",
    headerLanguage: "Language",
    headerLocation: "You are at:",
    ongSectionTitle: "Support Local NGOs",
    ongSectionSubtitle: "Does your NGO help animals? Join our platform to promote adoptable pets and receive community support.",
    ongBtn: "Register My NGO",
    ongFormTitle: "NGO Registration",
    ongFormDesc: "Fill in the details below to register your organization and help more animals.",
    ongName: "NGO Name",
    ongCnpj: "Tax ID (CNPJ)",
    ongDescription: "Organization Description",
    ongRegisterSuccess: "Registration successful! We will contact you soon.",
    viewOngsBtn: "View Registered NGOs",
    invalidCnpj: "Invalid Tax ID format.",
    invalidTaxId: "Invalid registration number.",
    registeredOngsTitle: "Partner NGOs",
    seeAllOngs: "See all NGOs",
    partnerOngs: "Partner NGOs",
    searchOngsPlaceholder: "Search NGOs by city, state or name",
    noOngsFound: "No NGOs found matching your criteria.",
    viewOng: "View NGO",
    aboutOng: "About the NGO",
    contactOng: "Contact",
    availablePets: "Pets for Adoption",
    donateBtn: "Donate",
    copyPix: "Copy Pix Key",
    pixCopied: "Pix Key copied!",
    bankDetails: "Bank Details",
    bankName: "Bank",
    agency: "Agency",
    account: "Account",
    prevPage: "Previous",
    nextPage: "Next",
    pageOf: "of",
    watchVideo: "Watch Video",
    pauseVideo: "Pause Video",
    verifyLocationBtn: "Verify Location",
    locationMatch: "Location Verified! You are at the profile location.",
    locationMismatch: "Warning: Your current location differs from profile.",
    verifying: "Verifying...",
    lostFoundTitle: "Lost & Found",
    lostFoundSubtitle: "Help reunite lost pets with their owners.",
    reportLost: "Report Lost Pet",
    reportFound: "Report Found Pet",
    noLostPets: "No missing pets reported in your area.",
    myOngsTitle: "My Registered NGOs",
    noMyOngs: "You haven't registered any NGOs yet.",
    landingLostFoundTitle: "Lost or Found a Pet?",
    landingLostFoundSubtitle: "Our community can help! Use our geolocation-based Lost & Found tool to reunite pets.",
    landingLostFoundBtn: "Access Lost & Found",
    linkCopied: "Link copied!",
    viewMap: "View Map",
    viewList: "View List",
    adoptionSuccessTitle: "Interest Registered!",
    adoptionSuccessMsg: "Your contact has been sent to the NGO/Owner. They will contact you shortly.",
    tabOverview: "Overview",
    tabTransparency: "Transparency Portal",
    totalRaised: "Total Raised (Month)",
    totalExpenses: "Total Expenses",
    activeDonors: "Active Donors",
    monthlyBreakdown: "Cost Breakdown",
    expenseFood: "Food & Supplies",
    expenseVet: "Vet & Exams",
    expenseMaintenance: "Shelter Maintenance",
    expenseMeds: "Medication",
    howToHelpTitle: "Other Ways to Help",
    helpTip1: "Volunteer to walk dogs",
    helpTip2: "Donate cleaning supplies or food",
    helpTip3: "Share our pets on social media",
    locationMap: "Location",
    invalidFileType: "Invalid file type. Only images are allowed.",
    fileTooLarge: "File too large. Maximum size is 5MB.",
    scheduleTitle: "Book Service",
    selectDate: "Select Date",
    selectTime: "Select Time",
    confirmBooking: "Confirm Booking",
    bookingSuccess: "Booking confirmed successfully!",
    landingServicesTitle: "We take care of everything for you",
    landingServicesSubtitle: "Find the best services for your pet, book easily, and enjoy exclusive discounts.",
    landingServicesBtn: "View Plans",
    landingDatingTitle: "Love is in the Air",
    landingDatingSubtitle: "Find the perfect match for your pet. With AnyPremium, you can find partners based on breed, age, and location for dating or breeding.",
    landingDatingBtn: "Explore Premium Plan"
  },
  [Language.ES]: {
    heroTitle: "El Mundo de tu Mascota en un Solo Lugar",
    heroSubtitle: "Conecta, cuida y ama. La plataforma completa para tu mejor amigo.",
    ctaStart: "Empezar Ahora",
    ctaLogin: "Ingresar",
    planBasic: "AnyBasic",
    planStart: "AnyStart",
    planPremium: "AnyPremium",
    perMonth: "/mes",
    features: "Características",
    loginTitle: "Acceso",
    email: "Correo",
    password: "Clave",
    loginButton: "Entrar a la Plataforma",
    dashHome: "Inicio",
    dashAdoption: "Adopción",
    dashDating: "Citas",
    dashHealth: "Cartilla",
    dashServices: "Servicios",
    dashProfile: "Perfil de Mascota",
    dashLostFound: "Perdidos y Encontrados",
    dashMyOngs: "Mis ONG",
    logout: "Salir",
    welcome: "Bienvenido de nuevo",
    myPets: "Mis Mascotas",
    vaccines: "Vacinas",
    serviceVet: "Veterinarios",
    serviceGroom: "Peluquería",
    serviceHotel: "Hoteles",
    serviceWalker: "Paseadores",
    bookNow: "Reservar",
    adoptMe: "Adóptame",
    match: "Coincidir",
    generateBio: "Generar Bio con IA",
    bioPlaceholder: "Escribe sobre tu mascota...",
    priceFree: "Gratis",
    priceStart: "$9.90",
    pricePremium: "$19.90",
    popular: "POPULAR",
    featProfile: "Perfil de Mascota",
    featAdoption: "Acceso a Adopción",
    featBasic: "Todo lo de Basic",
    featVaccines: "Cartilla de Vacunación",
    featScheduling: "Reserva de Servicios",
    featStart: "Todo lo de Start",
    featDating: "Citas / Cría",
    featAIBio: "Generador de Bio IA",
    featSupport: "Soporte Prioritário",
    featLostFound: "Perdidos y Encontrados",
    featOngRegister: "Registro de ONG",
    btnChooseBasic: "Elegir Basic",
    btnChooseStart: "Elegir Start",
    btnChoosePremium: "Elegir Premium",
    signupTitle: "Crear Cuenta",
    name: "Nombre Completo",
    confirmPassword: "Confirmar Clave",
    signupButton: "Registrarse",
    haveAccount: "¿Ya tienes cuenta? Ingresar",
    noAccount: "¿No tienes cuenta? Regístrate",
    createAccount: "Crear Cuenta",
    editProfile: "Editar Perfil",
    saveChanges: "Guardar Cambios",
    cancel: "Cancelar",
    weight: "Peso (kg)",
    photoUrl: "URL de Foto",
    ageLabel: "Edad (años)",
    breedLabel: "Raza",
    changePhoto: "Cambiar Foto",
    userProfile: "Datos del Dueño",
    switchPet: "Cambiar Mascota",
    addNewPet: "Agregar Nueva Mascota",
    noPets: "No se encontraron mascotas",
    createFirstPet: "Registra tu primera mascota",
    userSettings: "Mi Cuenta",
    phone: "Teléfono",
    petName: "Nombre de Mascota",
    petType: "Tipo de Animal",
    selectPet: "Selecciona una Mascota",
    deletePet: "Eliminar Mascota",
    confirmDeletePet: "¿Estás seguro de que deseas eliminar esta mascota? Esta acción no se puede deshacer.",
    deletePetWarning: "Eliminar permanentemente este perfil",
    currentPlan: "Plan Actual",
    upgradePlan: "Cambiar Plan",
    planBenefits: "Beneficios de tu plan",
    managePlan: "Gestionar Suscripción",
    typeDog: "Perro",
    typeCat: "Gato",
    typeBird: "Pájaro",
    typeOther: "Otro",
    healthVaccine: "Vacuna",
    healthDate: "Fecha de Aplicación",
    healthNextDue: "Próxima Dosis",
    healthStatus: "Estado",
    healthNoRecords: "No se encontraron registros de vacunas.",
    healthTip: "Consejo: Mantén la cartilla de vacunación actualizada para acceder a hoteles y guarderías.",
    planDescBasic: "Perfil, Adopción, ONG y Perdidos/Encontrados",
    planDescStart: "Vacunas, Reservas y Funciones Básicas",
    planDescPremium: "Acceso Total, Citas, IA y Soporte",
    availableForDatingLabel: "Disponible para Citas/Cría",
    datingPlanWarning: "¡Función exclusiva del plan Premium!",
    featureLocked: "Función Bloqueada",
    upgradeToAccess: "Mejora tu plan para acceder a esta función.",
    unlockNow: "Desbloquear Agora",
    tooltipProfile: "Gestiona la información y fotos de tu mascota.",
    tooltipAdoption: "Encuentra un nuevo amigo o adopta.",
    tooltipDating: "Encuentra la pareja perfecta para tu mascota.",
    tooltipHealth: "Seguimiento de vacunas y salud.",
    tooltipServices: "Reserva veterinarios, peluquería y más.",
    reqPlanBasic: "Plan Basic o superior",
    reqPlanStart: "Requiere Plan Start",
    reqPlanPremium: "Requiere Plan Premium",
    landingAdoptionTitle: "Encuentra tu nuevo mejor amigo",
    landingAdoptionSubtitle: "Cientos de mascotas esperan un hogar lleno de amor. Haz la diferencia hoy.",
    landingAdoptionBtn: "Ver Mascotas en Adopción",
    publicAdoptionTitle: "Adopción Responsable",
    publicAdoptionSubtitle: "Estos amigos buscan un hogar. Navega, enamórate y contáctanos.",
    backToHome: "Volver al Inicio",
    interestBtn: "Me Interesa",
    locationLabel: "Ubicación",
    getLocationBtn: "Actualizar con GPS",
    locationError: "Error al obtener ubicación. Revisa permisos.",
    kmAway: "km de distancia",
    locationUpdated: "¡Ubicación actualizada con éxito!",
    selectedPlanLabel: "Plan Seleccionado",
    passwordStrength: "Seguridad de clave",
    weak: "Débil",
    medium: "Media",
    strong: "Fuerte",
    acceptTerms: "Leí y acepto los",
    termsLink: "Términos de Uso",
    privacyLink: "Política de Privacidade",
    termsError: "Debes aceptar los términos para continuar.",
    termsTitle: "Términos de Uso",
    privacyTitle: "Política de Privacidad",
    emailError: "Por favor, introduzca un correo electrónico válido.",
    myFavorites: "Mis Favoritos",
    noFavorites: "Aún no has marcado ninguna mascota como favorita.",
    footerRights: "Todos los derechos reservados",
    footerCompany: "Empresa",
    footerLegal: "Legal",
    footerAbout: "Sobre Nosotros",
    footerContact: "Contacto",
    footerFollowUs: "Síguenos",
    footerBlog: "Blog",
    footerCareers: "Carreras",
    footerHelp: "Centro de Ayuda",
    searchLocationPlaceholder: "Buscar por Código Postal o Ciudad",
    searchBtn: "Buscar",
    locationNotFound: "Ubicación no encontrada. Usando ubicación predeterminada.",
    filterAll: "Todos",
    filterType: "Filtrar por tipo",
    minRating: "Valoración Mín.",
    clearFilters: "Limpar Filtros",
    detecting: "Detectando...",
    setLocation: "Establecer Ubicación",
    headerLanguage: "Idioma",
    headerLocation: "Estás en:",
    ongSectionTitle: "Apoya a las ONG Locales",
    ongSectionSubtitle: "¿Tu ONG ayuda animales? Únete a nuestra plataforma para promover mascotas adoptables y recibir apoyo.",
    ongBtn: "Registrar mi ONG",
    ongFormTitle: "Registro de ONG",
    ongFormDesc: "Complete los detalles a continuación para registrar su organización y ayudar a más animales.",
    ongName: "Nombre de la ONG",
    ongCnpj: "RUC / ID Fiscal",
    ongDescription: "Descripción de la Organización",
    ongRegisterSuccess: "¡Registro exitoso! Nos pondremos en contacto pronto.",
    viewOngsBtn: "Ver ONG registradas",
    invalidCnpj: "ID Fiscal inválido.",
    invalidTaxId: "Número de registro inválido.",
    registeredOngsTitle: "ONG Asociadas",
    seeAllOngs: "Ver todas las ONG",
    partnerOngs: "ONG Asociadas",
    searchOngsPlaceholder: "Buscar ONG por ciudad, estado o nombre",
    noOngsFound: "No se encontraron ONG con estos criterios.",
    viewOng: "Ver ONG",
    aboutOng: "Sobre la ONG",
    contactOng: "Contacto",
    availablePets: "Mascotas en Adopción",
    donateBtn: "Donar",
    copyPix: "Copiar Clave Pix",
    pixCopied: "¡Clave Pix copiada!",
    bankDetails: "Datos Bancarios",
    bankName: "Banco",
    agency: "Agencia",
    account: "Cuenta",
    prevPage: "Anterior",
    nextPage: "Siguiente",
    pageOf: "de",
    watchVideo: "Ver Video",
    pauseVideo: "Pausar Video",
    verifyLocationBtn: "Verificar Ubicación",
    locationMatch: "¡Ubicación verificada! Estás en la ubicación del perfil.",
    locationMismatch: "Advertencia: Tu ubicación actual difere do la del perfil.",
    verifying: "Verificando...",
    lostFoundTitle: "Perdidos y Encontrados",
    lostFoundSubtitle: "Ayuda a reunir mascotas perdidas con sus dueños.",
    reportLost: "Reportar Perdido",
    reportFound: "Reportar Encontrado",
    noLostPets: "No hay mascotas perdidas reportadas en tu área.",
    myOngsTitle: "Mis ONG Registradas",
    noMyOngs: "Aún no has registrado ninguna ONG.",
    landingLostFoundTitle: "¿Perdió o encontró una mascota?",
    landingLostFoundSubtitle: "¡Nuestra comunidad puede ayudar! Utiliza nuestra herramienta de Objetos Perdidos basada en geolocalización.",
    landingLostFoundBtn: "Acceder a Perdidos y Encontrados",
    linkCopied: "¡Enlace copiado!",
    viewMap: "Ver Mapa",
    viewList: "Ver Lista",
    adoptionSuccessTitle: "¡Interés Registrado!",
    adoptionSuccessMsg: "Tu contacto ha sido enviado a la ONG/Responsável. Te contactarán pronto.",
    tabOverview: "Visión General",
    tabTransparency: "Portal de Transparencia",
    totalRaised: "Total Recaudado (Mes)",
    totalExpenses: "Gastos Totales",
    activeDonors: "Donantes Activos",
    monthlyBreakdown: "Desglose de Costos",
    expenseFood: "Alimentos y Suministros",
    expenseVet: "Veterinaria y Exámenes",
    expenseMaintenance: "Mantenimiento del Refugio",
    expenseMeds: "Medicamentos",
    howToHelpTitle: "Otras Formas de Ayudar",
    helpTip1: "Sea voluntario para pasear perros",
    helpTip2: "Done artículos de limpieza o comida",
    helpTip3: "Comparte nuestras mascotas en las redes",
    locationMap: "Ubicación",
    invalidFileType: "Tipo de archivo inválido. Solo se permiten imágenes.",
    fileTooLarge: "Archivo demasiado grande. El tamaño máximo es 5MB.",
    scheduleTitle: "Reservar Servicio",
    selectDate: "Seleccionar Fecha",
    selectTime: "Seleccionar Hora",
    confirmBooking: "Confirmar Reserva",
    bookingSuccess: "¡Reserva confirmada con éxito!",
    landingServicesTitle: "Nos ocupamos de todo por ti",
    landingServicesSubtitle: "Encuentra los mejores servicios para tu mascota, reserva fácilmente y disfruta de descuentos exclusivos.",
    landingServicesBtn: "Conocer Planes",
    landingDatingTitle: "El Amor está en el Aire",
    landingDatingSubtitle: "Encuentra la pareja perfecta para tu mascota. Con AnyPremium, puedes encontrar compañeros basados en raza, edad y ubicación.",
    landingDatingBtn: "Conocer Plan Premium"
  }
};

// Base location: São Paulo (-23.5505, -46.6333) for mock data
export const MOCK_ADOPTION_PETS: Pet[] = [
  { id: '1', name: 'Thor', breed: 'Golden Retriever', age: 2, type: 'dog', image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=400&q=80', bio: 'Friendly and energetic.', location: { lat: -23.5605, lng: -46.6433 }, ongId: '1' }, // Near Paulista
  { id: '2', name: 'Luna', breed: 'Siamese', age: 1, type: 'cat', image: 'https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&w=400&q=80', bio: 'Quiet and loving.', location: { lat: -23.5405, lng: -46.6233 }, ongId: '2' },
  { id: '3', name: 'Bob', breed: 'Bulldog', age: 4, type: 'dog', image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=400&q=80', bio: 'Loves sleeping.', location: { lat: -23.5705, lng: -46.6533 }, ongId: '1' },
  { id: '6', name: 'Paçoca', breed: 'Vira-lata', age: 2, type: 'dog', image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=400&q=80', bio: 'Alegre e brincalhão.', location: { lat: -23.5805, lng: -46.6333 }, ongId: '1' },
  { id: '7', name: 'Simba', breed: 'Persa', age: 3, type: 'cat', image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=400&q=80', bio: 'Rei da casa.', location: { lat: -22.9068, lng: -43.1729 }, ongId: '2' },
];

export const MOCK_DATING_PETS: Pet[] = [
  { id: '4', name: 'Bella', breed: 'Poodle', age: 3, type: 'dog', image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=400&q=80', bio: 'Looking for a playdate.', location: { lat: -23.5555, lng: -46.6355 } },
  { id: '5', name: 'Max', breed: 'German Shepherd', age: 3, type: 'dog', image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?auto=format&fit=crop&w=400&q=80', bio: 'Very active and protective.', location: { lat: -23.5805, lng: -46.6133 } },
];

export const MOCK_SERVICES: ServiceProvider[] = [
  { id: '1', name: 'Dr. Dolittle Clinic', type: 'veterinarian', rating: 4.8, image: 'https://picsum.photos/200/200?random=10', location: { lat: -23.5615, lng: -46.6559 }, address: 'Av. Paulista, 1000' },
  { id: '2', name: 'Happy Paws Grooming', type: 'petshop', rating: 4.5, image: 'https://picsum.photos/200/200?random=11', location: { lat: -23.5505, lng: -46.6333 }, address: 'Centro Histórico' },
  { id: '3', name: 'Walkies with Sarah', type: 'dogwalker', rating: 5.0, image: 'https://picsum.photos/200/200?random=12', location: { lat: -23.5905, lng: -46.6733 }, address: 'Vila Olímpia' },
  { id: '4', name: 'Pet Paradise Hotel', type: 'hotel', rating: 4.7, image: 'https://picsum.photos/200/200?random=13', location: { lat: -23.5205, lng: -46.6033 }, address: 'Santana' },
];

export const MOCK_DAILY_PHOTOS = [
  { url: 'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?q=80&w=1000&auto=format&fit=crop', petName: 'Rex', breed: 'Golden Retriever', location: 'São Paulo, SP' },
  { url: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?q=80&w=1000&auto=format&fit=crop', petName: 'Mia', breed: 'Persa', location: 'Rio de Janeiro, RJ' },
  { url: 'https://images.unsplash.com/photo-1453227588063-bb302b62f50b?q=80&w=1000&auto=format&fit=crop', petName: 'Buddy', breed: 'Bulldog Francês', location: 'Curitiba, PR' },
  { url: 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?q=80&w=1000&auto=format&fit=crop', petName: 'Thor', breed: 'Husky Siberiano', location: 'Belo Horizonte, MG' },
];

// Updated MOCK_ONGS with reliable Unsplash images and coordinates
export const MOCK_ONGS: Ong[] = [
  { 
    id: '1', 
    name: 'Anjos de Patas', 
    image: 'https://images.unsplash.com/photo-1593134257782-e89567b7718a?auto=format&fit=crop&w=400&q=80', 
    description: 'Resgatando e cuidando de cães de rua há 10 anos.', 
    location: 'São Paulo, SP', 
    coordinates: { lat: -23.5505, lng: -46.6333 },
    pixKey: 'anjos@patas.org.br', 
    phone: '(11) 99999-0001', 
    email: 'contato@anjosdepatas.org.br', 
    bankInfo: { bank: 'Banco do Brasil', agency: '1234-X', account: '56789-0' },
    financials: {
        revenue: 15400,
        expenses: 14200,
        donors: 124,
        breakdown: { food: 5000, vet: 6000, maintenance: 2000, meds: 1200 }
    }
  },
  { 
    id: '2', 
    name: 'Gatinhos da Vila', 
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=400&q=80', 
    description: 'Lar temporário e adoção para felinos.', 
    location: 'Rio de Janeiro, RJ', 
    coordinates: { lat: -22.9068, lng: -43.1729 },
    pixKey: 'gatinhos@vila.com', 
    phone: '(21) 98888-0002', 
    email: 'adote@gatinhosdavila.com',
    financials: {
        revenue: 8500,
        expenses: 9100,
        donors: 56,
        breakdown: { food: 3000, vet: 3500, maintenance: 1500, meds: 1100 }
    }
  },
  { 
    id: '3', 
    name: 'Amigo Fiel', 
    image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=400&q=80', 
    description: 'Reabilitação e adoção de animais feridos.', 
    location: 'Curitiba, PR', 
    coordinates: { lat: -25.4244, lng: -49.2654 },
    pixKey: 'amigo@fiel.org', 
    phone: '(41) 97777-0003',
    financials: {
        revenue: 22000,
        expenses: 18000,
        donors: 210,
        breakdown: { food: 6000, vet: 8000, maintenance: 3000, meds: 1000 }
    }
  },
  { 
    id: '4', 
    name: 'Santuário Animal', 
    image: 'https://images.unsplash.com/photo-1548681528-6a5c45b66b42?auto=format&fit=crop&w=400&q=80', 
    description: 'Proteção para animais de grande porte e silvestres.', 
    location: 'Belo Horizonte, MG', 
    coordinates: { lat: -19.9167, lng: -43.9345 },
    pixKey: 'santuario@animal.org', 
    phone: '(31) 96666-0004' 
  },
  { 
    id: '5', 
    name: 'Vira-lata Caramelo', 
    image: 'https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=400&q=80', 
    description: 'Apoio a cães comunitários.', 
    location: 'Salvador, BA',
    coordinates: { lat: -12.9777, lng: -38.5016 }
  },
  { 
    id: '6', 
    name: 'Arca de Noé', 
    image: 'https://images.unsplash.com/photo-1596272875729-ed2c21d50510?auto=format&fit=crop&w=400&q=80', 
    description: 'Abrigo para todos os tipos de animais.', 
    location: 'Porto Alegre, RS',
    coordinates: { lat: -30.0346, lng: -51.2177 }
  },
  { 
    id: '7', 
    name: 'Cão Sem Dono', 
    image: 'https://images.unsplash.com/photo-1534361960057-19889db9621e?auto=format&fit=crop&w=400&q=80', 
    description: 'Resgate de animais em situação de risco.', 
    location: 'Recife, PE',
    coordinates: { lat: -8.0476, lng: -34.8770 }
  },
  { 
    id: '8', 
    name: 'Adote um Gatinho', 
    image: 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?auto=format&fit=crop&w=400&q=80', 
    description: 'Maior ONG de resgate de gatos do Brasil.', 
    location: 'São Paulo, SP',
    coordinates: { lat: -23.5505, lng: -46.6333 }
  },
  { 
    id: '9', 
    name: 'Protetores Independentes', 
    image: 'https://images.unsplash.com/photo-1535930749574-1399327ce78f?auto=format&fit=crop&w=400&q=80', 
    description: 'Grupo de voluntários unidos pela causa animal.', 
    location: 'Florianópolis, SC',
    coordinates: { lat: -27.5954, lng: -48.5480 }
  },
  { 
    id: '10', 
    name: 'Amor de Bicho', 
    image: 'https://images.unsplash.com/photo-1599443015574-be5fe8a05783?auto=format&fit=crop&w=400&q=80', 
    description: 'Castração e conscientização.', 
    location: 'Campinas, SP',
    coordinates: { lat: -22.9099, lng: -47.0626 }
  },
  { 
    id: '11', 
    name: 'Vida Animal', 
    image: 'https://images.unsplash.com/photo-1494913148647-3532a40bf239?auto=format&fit=crop&w=400&q=80', 
    description: 'Abrigo e hospital veterinário solidário.', 
    location: 'Fortaleza, CE',
    coordinates: { lat: -3.7172, lng: -38.5434 }
  },
  { 
    id: '12', 
    name: 'Patas Dadas', 
    image: 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=400&q=80', 
    description: 'Promovendo encontros felizes.', 
    location: 'Porto Alegre, RS',
    coordinates: { lat: -30.0346, lng: -51.2177 }
  },
  { 
    id: '13', 
    name: 'SOS Animais', 
    image: 'https://images.unsplash.com/photo-1529472119196-cb724127a98e?auto=format&fit=crop&w=400&q=80', 
    description: 'Atendimento emergencial para animais de rua.', 
    location: 'Brasília, DF',
    coordinates: { lat: -15.7975, lng: -47.8919 }
  },
  { 
    id: '14', 
    name: 'Bicho Feliz', 
    image: 'https://images.unsplash.com/photo-1519052537078-e6302a4968ef?auto=format&fit=crop&w=400&q=80', 
    description: 'Felicidade é ter um lar.', 
    location: 'Manaus, AM',
    coordinates: { lat: -3.1190, lng: -60.0217 }
  },
  { 
    id: '15', 
    name: 'Resgate Pet', 
    image: 'https://images.unsplash.com/photo-1472491235688-bdc81a63246e?auto=format&fit=crop&w=400&q=80', 
    description: 'Resgate, reabilitação e amor.', 
    location: 'Goiânia, GO',
    coordinates: { lat: -16.6869, lng: -49.2648 }
  }
];